name: Build Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Install Dependencies (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ cmake libboost-locale-dev libboost-filesystem-dev libpng-dev libjpeg-dev zlib1g-dev libiconv-hook-dev libssl-dev libwebp-dev
          
      - name: Create Build Directory
        run: mkdir build
      - name: Configure CMake
        run: cmake -DCMAKE_BUILD_TYPE=Release -S . -B build

      - name: Build Project
        run: cmake --build build --parallel 8
        #&& ls build
        
      - name: Upload files
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          replacesArtifacts: false
          #tag: z${{ env.BUILD }}
          commit: true
          #name: ONScripter-ru r${{ env.BUILD }}
          artifacts: "build/arc_unpacker"
